version: 2.1
jobs:
  build:
    docker:
      - image: golang:1.14
    steps:
      - checkout
      - run:
          name: Running tests
          command: make _test

      - run:
          name: Bulding
          command: make _build
